use rchip8::machine::insts::Chip8Inst;

grammar;

VarRegister: usize = r"V[0-9a-fA-F]" => usize::from_str_radix(&<>[1..], 16).unwrap();

Addr: usize = r"[0-9a-fA-F]+" => usize::from_str_radix(<>, 16).unwrap();

pub Instruction: Chip8Inst = {
    "clr" => Chip8Inst::ClearScreen,
    "retn" => Chip8Inst::SubReturn,
    "jump" <Addr> => Chip8Inst::Jump(<>),
    "call" <Addr> => Chip8Inst::SubCall(<>),
    "mov" <x:VarRegister> "," <y:VarRegister> => Chip8Inst::Assign(x, y),
};
